# Global plugin options (will be passed to all plugins)
preset: "conventionalcommits"

# Plugin configurations
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"

# Branch configurations
branches:
  - "main"
  - name: "develop"
    prerelease: "preview"

# Responsible for generating the content of the release notes
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort: "title"
      commitsSort: "header"
    linkCompare: true
    linkReferences: true
    presetConfig:
      types: # only works with "conventionalcommits" preset
        - type: "build"
          section: "⚙️ CI/CD"
        - type: "chore"
          section: "✨ Other"
        - type: "ci"
          section: "⚙️ CI/CD"
        - type: "docs"
          section: "📔 Docs"
        - type: "example"
          section: "📝 Examples"
        - type: "feat"
          section: "🚀 Features"
        - type: "fix"
          section: "🛠 Fixes"
        - type: "perf"
          section: "⏩ Performance"
        - type: "refactor"
          section: "✂ Refactor"
        - type: "revert"
          section: "🙅‍️ Reverts"
        - type: "style"
          section: "💈 Style"
        - type: "test"
          section: "🧪 Tests"
